[project]
name = "house-price-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "kagglehub>=0.3.12",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "xgboost>=3.0.2",
]
